### ISSUE TITLE
Is this plugin the only way to import components with relative path, e.g. `./Components/AnotherComp`?

### ISSUE THREAD

**Issue by nyngwang** [jose-elias-alvarez/nvim-lsp-ts-utils#106]
As title. I currently using `nvim-cmp` and I found that the auto-import on confirm doesn't detect files under the same folder.

**Comment by jose-elias-alvarez** [comment]
This behavior is fundamentally controlled by `typescript-language-server`, so I can't say for sure. You can see [here](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils/blob/64d233a8859e27139c55472248147114e0be1652/lua/nvim-lsp-ts-utils/import-on-completion.lua#L53) what we are doing to resolve imports. I'm not sure what nvim-cmp is doing, but it should be pretty similar, so I'm surprised there's a difference in behavior.

**Comment by nyngwang** [comment]
Many thanks for your help with the confirmation! OK, but since I'm relatively new to language-server so I don't know what to do now...

**Comment by jose-elias-alvarez** [comment]
Closing this issue as it's more of a question and not something we can act on.
