### ISSUE TITLE
[BUG] :TSLspImportAll and :TSLspImportCurrent doesn't working. 

### ISSUE THREAD

**Issue by singlexyz** [jose-elias-alvarez/nvim-lsp-ts-utils#112]
### FAQ

- [X] I have checked [troubleshooting](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils#troubleshooting) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils/issues?q=is%3Aissue+) and there are no issues with the same problem.

### Neovim Version

NVIM v0.6.1

### Steps to reproduce

```jsx
import React from "react"

function App() {
  const div = useRef(null)
}

export default App
```

Cursor on `useRef`, then execute `:TSLspImportAll` or `:TSLspImportCurrent`, nothing happen.
Buy actually I had those actions

<img width="758" alt="截屏2022-03-14 上午3 56 21" src="https://user-images.githubusercontent.com/4456413/158076711-06471f5e-69de-4d43-bd00-91cf4de3dd0f.png">

if execute them, it works.

### Expected behavior

Auto Import.

### Actual behavior

nothing happens.

### Debug log

```
Command git exited with code 0
No code actions available
```

jsconfig:
```
{
  "compilerOptions": {
    "checkJs": true,
    "jsx": "preserve"
  }
}
```

I made a recording:

https://user-images.githubusercontent.com/4456413/158076857-ead3e4fb-7d46-4e87-977c-7972aea9956a.mov

And here's my lsp config:
```
local capabilities = require("cmp_nvim_lsp").update_capabilities(vim.lsp.protocol.make_client_capabilities())
capabilities.textDocument.completion.completionItem.snippetSupport = true
capabilities.textDocument.completion.completionItem.resolveSupport = {
  properties = {
    "documentation",
    "detail",
    "additionalTextEdits",
  },
}

local nullls = require("null-ls")
nullls.setup({
  sources = {
    nullls.builtins.formatting.stylua.with({
      extra_args = { "--indent-type", "Spaces", "--indent-width", "2" },
    }),
    nullls.builtins.formatting.prettier_d_slim.with({
      extra_args = { "--bracket-spacing", true },
    }),
    nullls.builtins.code_actions.gitsigns,
    nullls.builtins.code_actions.refactoring,
  },
})

lspconfig.tsserver.setup({
  on_attach = function(client, bufnr)
  -- all copy from https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils#setup
  end,
  capabilities = capabilities,
  commands = {
    OrganizeImports = {
      organize_imports,
      description = "Organize Imports",
    },
  },

```

### Help

No

**Comment by jose-elias-alvarez** [comment]
Your example does work for me, both on a production project and on a blank skeleton project. There's too many potential variables (versions, project configurations / structures) for me to figure out exactly what's going on. I can see that your `tsserver` code actions are slightly different from the ones I get:

<img width="427" alt="Screen Shot 2022-03-13 at 6 22 35 PM" src="https://user-images.githubusercontent.com/54108223/158081688-77c68fb3-92d1-478b-acb8-b6d9c042a421.png">

This leads me to believe that something about your local environment is causing this not to work. If you can put together a repository containing the code I need to replicate this, including the necessary versions of all the dependencies (React and TypeScript), I'm happy to look into this more.

**Comment by sinnrrr** [comment]
+1, having the same issue and configuration as the author, `:TSLspImportAll` and `:TSLspImportCurrent` doesn't work even if the cursor is on the unimported part of the code

however `:TSLspOrganize` and `:TSLspRenameFile` seem to work fine

**Comment by singlexyz** [comment]
> Your example does work for me, both on a production project and on a blank skeleton project. There's too many potential variables (versions, project configurations / structures) for me to figure out exactly what's going on. I can see that your `tsserver` code actions are slightly different from the ones I get:
> 
> <img alt="Screen Shot 2022-03-13 at 6 22 35 PM" width="427" src="https://user-images.githubusercontent.com/54108223/158081688-77c68fb3-92d1-478b-acb8-b6d9c042a421.png">
> 
> This leads me to believe that something about your local environment is causing this not to work. If you can put together a repository containing the code I need to replicate this, including the necessary versions of all the dependencies (React and TypeScript), I'm happy to look into this more.



> This leads me to believe that something about your local environment is causing this not to work. If you can put together a repository containing the code I need to replicate this, including the necessary versions of all the dependencies (React and TypeScript), I'm happy to look into this more.

Yeah, it's a project create from vite:
```
yarn create vite@latest my-app
```
framework and variant options  select `react` both.
and also `create-react-app` also the same.
```
npx create-react-app my-app
```

Same jsconfig.json
```
{
  "compilerOptions": {
    "checkJs": true,
    "jsx": "react"
  }
}
```

**Comment by jose-elias-alvarez** [comment]
I see, I didn't realize you were using JavaScript. I can replicate this on a new CRA project that's not initialized with TypeScript. I briefly looked into this and the issue seems to be that the title of the actions doesn't match the TypeScript equivalent, so `:TSLspImportAll` ignores it. 

JavaScript support in this plugin is, at best, accidental, since I don't personally use JavaScript and there's a ton of edge cases like this. If it's possible to add support without increasing complexity, I'm happy to review a PR, but I don't plan on fixing this myself. I'll also add a note to the README to specify that only TypeScript is officially supported.

**Comment by sinnrrr** [comment]
@jose-elias-alvarez [I have fully typescript project bootstrapped with `npx create-next-app` here](https://github.com/sinnrrr/debug/tree/vim-no-import) , `_app.tsx` file - `AppProps` doesn't import neither using `:TSLspImportAll` nor `:TSLspImportCurrent`

can you confirm this?

**Comment by jose-elias-alvarez** [comment]
> @jose-elias-alvarez [I have fully typescript project bootstrapped with `npx create-next-app` here](https://github.com/sinnrrr/debug/tree/vim-no-import), `_app.tsx` file - `AppProps` can't be imported neither using `:TSLspImportAll` nor `:TSLspImportCurrent`, although we have import code action available
> 
> can you confirm this?

Excellent, this repo is exactly what I needed to figure this out. Can you try #115?
