### ISSUE TITLE
[BUG] The command :TSLspOrganize does not import a missing import statement.

### ISSUE THREAD

**Issue by stephaneeybert** [jose-elias-alvarez/nvim-lsp-ts-utils#117]
### FAQ

- [X] I have checked [troubleshooting](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils#troubleshooting) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils/issues?q=is%3Aissue+) and there are no issues with the same problem.

### Neovim Version

v0.6.1

### Steps to reproduce

Make sure an import statement is missing.
Delete an existing import statement.
Wait for the LSP to load and underline the then undeclared variables.
Type in command `:TSLspOrganize`

The two other commands `:TSLspImportAll` and `:TSLspImportCurrent` work perfectly fine.

### Expected behavior

The command `:TSLspOrganize` should import a missing import statement.

### Actual behavior

The command `:TSLspOrganize` does not import a missing import statement.

### Debug log

As a neovim noob I could not see how to enable the trouble shooting debug option, nor where could I find some `:message` in some output. What is this output ? How to view it ?

### Help

No

**Comment by stephaneeybert** [comment]
The typescript language server that I installed is [tsserver](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#tsserver)

**Comment by jose-elias-alvarez** [comment]
The purpose of `:TSLspOrganize` is to organize existing import statements. To add new ones, you'll want to use one of the other commands (those commands also organize imports, but that's a side effect of how they work in the first place).
