### ISSUE TITLE
Function braces completion

### ISSUE THREAD

**Issue by kuator** [jose-elias-alvarez/nvim-lsp-ts-utils#12]
One of the featues I miss from https://github.com/sourcegraph/javascript-typescript-langserver is parentheses completion. Would it be possible to add an option to enable this in nvim-lsp-ts-utils?

**Comment by jose-elias-alvarez** [comment]
This is an interesting feature. Let me take a look at the implementation this weekend and get back to you re: feasibility/ scope.

**Comment by kuator** [comment]
> This is an interesting feature. Let me take a look at the implementation this weekend and get back to you re: feasibility/ scope.

Thanks!

**Comment by kuator** [comment]
Some more context: https://github.com/microsoft/pylance-release/issues/37

**Comment by folke** [comment]
The code below makes it work with compe 🙂

```lua
local Helper = require "compe.helper"
Helper.convert_lsp_orig = Helper.convert_lsp
Helper.convert_lsp = function(args)
  local response = args.response or {}
  local items = response.items or response
  for _, item in ipairs(items) do
    -- 2: method
    -- 3: function
    -- 4: constructor
    if item.insertText == nil and (item.kind == 2 or item.kind == 3 or item.kind == 4) then
      item.insertText = item.label .. "(${1})"
      item.insertTextFormat = 2
    end
  end
  return Helper.convert_lsp_orig(args)
end
```

**Comment by kuator** [comment]
> The code below makes it work with compe slightly_smiling_face
> 
> ```lua
> local Helper = require "compe.helper"
> Helper.convert_lsp_orig = Helper.convert_lsp
> Helper.convert_lsp = function(args)
>   local response = args.response or {}
>   local items = response.items or response
>   for _, item in ipairs(items) do
>     -- 2: method
>     -- 3: function
>     -- 4: constructor
>     if item.insertText == nil and (item.kind == 2 or item.kind == 3 or item.kind == 4) then
>       item.insertText = item.label .. "(${1})"
>       item.insertTextFormat = 2
>     end
>   end
>   return Helper.convert_lsp_orig(args)
> end
> ```

This works, but then I have to update the function every time it changes upstream?

**Comment by jose-elias-alvarez** [comment]
> The code below makes it work with compe 🙂
> 
> ```lua
> local Helper = require "compe.helper"
> Helper.convert_lsp_orig = Helper.convert_lsp
> Helper.convert_lsp = function(args)
>   local response = args.response or {}
>   local items = response.items or response
>   for _, item in ipairs(items) do
>     -- 2: method
>     -- 3: function
>     -- 4: constructor
>     if item.insertText == nil and (item.kind == 2 or item.kind == 3 or item.kind == 4) then
>       item.insertText = item.label .. "(${1})"
>       item.insertTextFormat = 2
>     end
>   end
>   return Helper.convert_lsp_orig(args)
> end
> ```

Thank you, this is very helpful!

The current implementation in the plugin listens for `CompleteDone`, which means that the text has already been inserted into the buffer by the time it gets access to this information. If we only need to handle adding parentheses, it would be pretty simple to append `()` to the end of the completion item after the fact and move the cursor into it. 

Are there any other cases that you'd like to see handled?

**Comment by folke** [comment]
It would probably be better to intercept the return values from `tsserver` and fixing them like I did on `compe` directlly.

That way, other plugins would also benefit from the change.

But your suggestion definitely also works and simpler to implement.

**Comment by folke** [comment]
Just looked for a better way to intercept this and the code below works as expected:

```lua
client.request_orig = client.request
    client.request = function(method, params, handler, bufnr)
      local intercept = function(err, method, result, client_id, bufnr)
        if method == "textDocument/completion" then
          local response = result or {}
          local items = response.items or response
          for _, item in ipairs(items) do
            -- 2: method
            -- 3: function
            -- 4: constructor
            if item.insertText == nil and (item.kind == 2 or item.kind == 3 or item.kind == 4) then
              item.insertText = item.label .. "(${1})"
              item.insertTextFormat = 2
            end
          end
        end
        return handler(err, method, result, client_id, bufnr)
      end
      return client.request_orig(method, params, intercept, bufnr)
    end
```

It needs to be executed in the `on_attach` method for the `typescript` lsp server

**Comment by folke** [comment]
Hmmm, this is actually useful for all lsp clients.

Adding this also fixes completion for `lua` lsp and others 🙂

**Comment by folke** [comment]
Thinking more about this, my solution is generic and works for all clients, but needs additonal packages like `vsnip` and config:

```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
```

Your suggestion is far easier to simply provide completion out of the box for TS, so that's probably the way to go

**Comment by jose-elias-alvarez** [comment]
This looks like a great improvement for full-featured completion solutions. My goal here is not to compete with those but to make `omnifunc` a little bit more viable for anyone who wants to keep it light. I'll work on the parentheses feature for now and see how it can be improved in the future.

**Comment by jose-elias-alvarez** [comment]
I've just pushed a first draft of this onto the `develop` branch, including a simple extra feature to trigger signature completion after moving the cursor. Feedback appreciated!

**Comment by jose-elias-alvarez** [comment]
Just merged into `main` as an experimental feature. The behavior is still a little wonky and needs some smoothing out in edge cases, but it works surprisingly well given how simple the implementation is. Closing this for now, but let me know how it goes.
