### ISSUE TITLE
eslint diagnostics end of line

### ISSUE THREAD

**Issue by miguelski** [jose-elias-alvarez/nvim-lsp-ts-utils#14]
i know diagnostics is experimental just reporting my issue

eslint with prettier rule warning about no end of file line, as neovim behavior is don't show that line even when it exists, diagnostics has a false positive there, running eslint command directly or open on vscode doesn't have the error since there is actually a end of file line there.

![image](https://user-images.githubusercontent.com/72758941/115917720-4191cf80-a43c-11eb-8932-cebcd03a057d.png)

additional it works with lsp efm

neovim version
NVIM v0.5.0-dev+1274-gbb3372792
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by jose-elias-alvarez** [comment]
First, thanks for helping improve diagnostics! This is exactly the kind of help I'm looking for. 

I had no idea that Neovim (and Vim) had this behavior, but it seems like VS Code and other editors like Atom are actually defying standard Unix behavior by treating the final newline as if it represents an actual empty line. The plugin uses Neovim's `nvim_buf_get_lines` to get the buffer content directly, which *doesn't* seem to include the final newline (at least according to`cat -E`). 

I've just pushed a fix that simply appends a final newline to the content, which fixes the ESLint issue you described (hopefully without any unexpected side effects). Could you let me know if it works for you?

**Comment by miguelski** [comment]
just tried and is working fine, thank you. I will continue testing it, and i let you know if i find any side effect

**Comment by jose-elias-alvarez** [comment]
Awesome, thanks for confirming. Going to close this for now but feel free to open another issue if you run into any more problems.
