### ISSUE TITLE
Failed to parse eslint json

### ISSUE THREAD

**Issue by vuki656** [jose-elias-alvarez/nvim-lsp-ts-utils#15]
Hey, love the idea of the plugin. I tried to set it up but am getting the following error when I open a .ts file.

`nvim-lsp-ts-utils: Failed to parse eslint json output: ...te/pack/packer/start/nvim-lsp-ts-utils/lua/json/init.lua:151: unexpected character '' at line 1 col 1`

Do you maybe know why it's happening or how to fix it? 

I did some googling and it might be due to encoding, no idea how or why. 

Thanks for the cool work :)

![image](https://user-images.githubusercontent.com/8104698/115920815-fba82c00-a47a-11eb-88e7-bac449c2371d.png)

Config:

        local nvim_lsp = require "lspconfig"
        local ts_utils = require("nvim-lsp-ts-utils")
        
        nvim_lsp.tsserver.setup {
            on_attach = function(client, bufnr)
                client.resolved_capabilities.document_formatting = false
        
                ts_utils.setup {
                    disable_commands = false,
                    enable_import_on_completion = false,
                    import_on_completion_timeout = 5000,
                    eslint_bin = "eslint",
                    eslint_args = {"-f", "json", "--stdin", "--stdin-filename", "$FILENAME"},
                    eslint_enable_disable_comments = true,
        
                    -- eslint_enable_diagnostics = false,
                    -- eslint_diagnostics_debounce = 250,
                    -- enable_formatting = false,
                    -- formatter = "eslint",
                    -- formatter_args = {"--stdin-filepath", "$FILENAME"},
                    -- format_on_save = true,
                    -- no_save_after_format = false
                }
        
                -- no default maps, so you may want to define some here
                vim.api.nvim_buf_set_keymap(bufnr, "n", "gs", ":TSLspOrganize<CR>", {silent = true})
                vim.api.nvim_buf_set_keymap(bufnr, "n", "qq", ":TSLspFixCurrent<CR>", {silent = true})
                vim.api.nvim_buf_set_keymap(bufnr, "n", "gr", ":TSLspRenameFile<CR>", {silent = true})
                vim.api.nvim_buf_set_keymap(bufnr, "n", "gi", ":TSLspImportAll<CR>", {silent = true})
            end
        }
        
        vim.lsp.buf_request = ts_utils.buf_request

**Comment by jose-elias-alvarez** [comment]
Hmm, interesting. The error makes it sound as if your ESLint JSON output is simply empty, which shouldn't be the case, since even if there are no errors, it should still return a valid JSON object. 

Could you let me know what you see when you run `eslint -f json` directly from the command line?

**Comment by vuki656** [comment]
![image](https://user-images.githubusercontent.com/8104698/115953400-8a549180-a4eb-11eb-972b-a9235fa714fa.png)

I had to run it from node modules since It's not installed globally.

Anyways, not sure why it's an empty array. Could it be that it's not detecting eslintrc correctly?

Its placed in the root of the project, in format `.eslintrc.json`

**Comment by jose-elias-alvarez** [comment]
Ahh, I see the problem. The current implementation expects the ESLint binary to be available on your `$PATH`, meaning it won't detect locally installed binaries at all. It seems that when the subprocess attempts to run a nonexistent command, it returns an empty line, which explains your original output (though I can't explain the empty array). 

Do you have the option to install ESLint globally to see if that returns valid output? I also briefly tried setting `eslint_bin` to an absolute path pointing to `node_modules`, and it seems to work (though of course that's a lousy workaround for anything but debugging). 

I definitely want to add the ability to detect and use local binaries, so let me know and I can put something together.

**Comment by vuki656** [comment]
Yup that seems to fix the problem.

But now I'm getting this:
![image](https://user-images.githubusercontent.com/8104698/115953971-b32a5600-a4ee-11eb-9ced-d1f551020da9.png)

Here is the formatting config(nothing different from the whole one in the initial comment):

            eslint_enable_diagnostics = true,
            eslint_diagnostics_debounce = 250,
            enable_formatting = true,
            formatter = "eslint",
            formatter_args = {"--stdin-filepath", "$FILENAME"},
            format_on_save = true,
            no_save_after_format = false

Would I need to add anything else in order to make `:lua require'nvim-lsp-ts-utils'.fix_current()` format the file aka run `eslint --fix`

**Comment by jose-elias-alvarez** [comment]
Actually, `fix_current()` is for code actions (and I can totally see the confusion, so I'll think about how to clarify the difference). The way formatting is (currently) handled is by overriding `vim.lsp.buf_request`, which will then run `formatter` whenever you run `vim.lsp.buf.formatting()`. 

Running `eslint` as a formatter is a little tricky since vanilla `eslint` doesn't actually provide a way to send the fixed plain text to `stdout`. It has [a flag](https://eslint.org/docs/user-guide/command-line-interface#-fix-dry-run) that doesn't write to the file, but it seems to require outputting to JSON as an intermediate step. 

If you're able to use [eslint_d](https://github.com/mantoni/eslint_d.js/) (and I highly recommend it, especially if you plan on using ESLint code actions), it has a `--fix-to-stdout` flag that solves the problem completely. The following minimal config works for me:

```lua
local ts_utils = require("nvim-lsp-ts-utils")
ts_utils.setup {
    formatter = "eslint_d",
    formatter_args = {
        "--fix-to-stdout", "--stdin", "--stdin-filename", "$FILENAME"
    },
}
vim.lsp.buf_request = ts_utils.buf_request
```

If there's demand for formatting via vanilla ESLint, parsing the JSON is very straightforward, so I'll see what I can put together, but I also don't want to complicate the formatting situation. The most straightforward solution would probably be to limit the available options for `formatter` (since it's not like there's that many options for the JS ecosystem) and then have the plugin set arguments internally.

**Comment by vuki656** [comment]
Formatter works great with eslint_d and it's blazing fast so you should probably put that in the readme as a way to use it. I've heard from a lot of people that eslint_d is a lot faster than vanilla eslint.  If you'd line I can open a PR. 

For some reason I'm not getting any diagnostics messages in the code, but formatting works. Is there anything else I would need to adjust in order to get the diagnostics messages? 

Here is the config ATM: 

        local nvim_lsp = require "lspconfig"
        local ts_utils = require("nvim-lsp-ts-utils")
        
        nvim_lsp.tsserver.setup {
            on_attach = function(client, bufnr)
                client.resolved_capabilities.document_formatting = false
        
                ts_utils.setup {
                    disable_commands = false,
                    enable_import_on_completion = false,
                    import_on_completion_timeout = 5000,
                    eslint_bin = "eslint_d",
                    eslint_args = {"-f", "--stdin", "--stdin-filename", "$FILENAME"},
                    eslint_enable_disable_comments = true,
        
                    eslint_enable_diagnostics = true,
                    eslint_diagnostics_debounce = 250,
                    enable_formatting = true,
                    formatter = "eslint_d",
                    formatter_args = {
                        "--fix-to-stdout",
                        "--stdin",
                        "--stdin-filename",
                        "$FILENAME"
                    },
                    format_on_save = true,
                    no_save_after_format = false
                }
        
                -- no default maps, so you may want to define some here
                vim.api.nvim_buf_set_keymap(bufnr, "n", "gs", ":TSLspOrganize<CR>", {silent = true})
                vim.api.nvim_buf_set_keymap(bufnr, "n", "qq", ":TSLspFixCurrent<CR>", {silent = true})
                vim.api.nvim_buf_set_keymap(bufnr, "n", "gr", ":TSLspRenameFile<CR>", {silent = true})
                vim.api.nvim_buf_set_keymap(bufnr, "n", "gi", ":TSLspImportAll<CR>", {silent = true})
            end
        }
        
        vim.lsp.buf_request = ts_utils.buf_request


Also, you should put a donation button, I'd be happy to drop some bucks, for the cool plugin and for you taking the time to help. I'm very grateful as I never managed to get diagnostics to work fully with efm or diagnostics_languageserver.

**Comment by jose-elias-alvarez** [comment]
Much appreciated, but no need to worry about it. Just happy to help out. 

For diagnostics, I think you might have erased an argument in `eslint_args`. Everything else looks good, so if you set it back to the default value, that should hopefully fix it (and if not the plugin should give you an error message, but fingers crossed):

```lua
eslint_args = {"-f", "json", "--stdin", "--stdin-filename", "$FILENAME"}
```

**Comment by vuki656** [comment]
Sorry, I didn't notice :D 

Thanks for everything.
