### ISSUE TITLE
Error executing vim.scheadule lua callback

### ISSUE THREAD

**Issue by vuki656** [jose-elias-alvarez/nvim-lsp-ts-utils#18]
Hey, I'm getting the above-mentioned error on every non-ts file I open. 

![image](https://user-images.githubusercontent.com/8104698/115999967-878e9500-a5ee-11eb-822b-2c2c7fa69aff.png)

Is there any way to turn it off for non-ts files?

**Comment by jose-elias-alvarez** [comment]
So to make sure: is this happening when you open a non-TypeScript file *after* opening a TypeScript file?

If so, it's most likely related to #17. Could you try the `develop` branch of the plugin and see if it fixes it? (It also introduces a small but breaking change to the way ESLint integration is set up, so take a look at the readme, too).

**Comment by vuki656** [comment]
That fixes it.

But now formatting only works with `:lua require 'nvim-lsp-ts-utils'.format()` and no longer with `vim.lsp.buf.formatting()`

Also, I fixed the doc in #19 for client referencing in the new setup.

**Comment by jose-elias-alvarez** [comment]
Glad to know it helped, and nice catch with the documentation, too. Hopefully I can get this merged soon, but let me know if you run into any other issues.

With formatting: do you have `enable_formatting` set to `true` in your config? If not, could I take a look at your config again?

**Comment by jose-elias-alvarez** [comment]
FYI I've merged the fix for your first issue into `main`. Let me know about the second whenever you get a chance.

**Comment by vuki656** [comment]
> Glad to know it helped, and nice catch with the documentation, too. Hopefully I can get this merged soon, but let me know if you run into any other issues.
> 
> With formatting: do you have `enable_formatting` set to `true` in your config? If not, could I take a look at your config again?

Yup it's on. I can see something happening as there is a half a second lag when I run the command, but no formatting happens.

Here is the current config 

    local nvim_lsp = require "lspconfig"
    local ts_utils = require("nvim-lsp-ts-utils")
    
    nvim_lsp.tsserver.setup {
        on_attach = function(client, bufnr)
            client.resolved_capabilities.document_formatting = false
    
            ts_utils.setup {
                eslint_bin = "eslint_d",
                eslint_args = {"-f", "json", "--stdin", "--stdin-filename", "$FILENAME"},
                eslint_enable_disable_comments = true,
                eslint_enable_diagnostics = true,
                enable_formatting = true,
                formatter = "eslint_d",
                formatter_args = {
                    "--fix-to-stdout",
                    "--stdin",
                    "--stdin-filename",
                    "$FILENAME"
                },
                format_on_save = false,
            }
    
            ts_utils.setup_client(client)
        end
    }

**Comment by jose-elias-alvarez** [comment]
Just tried out your config, and I think the issue is `client.resolved_capabilities.document_formatting = false`. Deleting that makes `vim.lsp.buf.formatting` work for me (and it would make sense that the issue started with this refactor, since we're now modifying the client). Could you give that a try?

**Comment by vuki656** [comment]
Works.

It makes sense to remove it yeah since you are plugging into native ts formatting I assume. It was a leftover from when I was trying to set up efm.

Thanks for taking the time to help.

**Comment by jose-elias-alvarez** [comment]
Great, thanks for confirming! Let me know if you run into any other issues, since I need all the help I can get testing these features in the wild.
