### ISSUE TITLE
Updating imports on file move

### ISSUE THREAD

**Issue by jose-elias-alvarez** [jose-elias-alvarez/nvim-lsp-ts-utils#20]
I originally wanted to implement this with [Watchman](https://facebook.github.io/watchman/), but the author of [fwatch.nvim](https://github.com/rktjmp/fwatch.nvim) showed me that luv can watch files from within Neovim with significantly less overhead and complexity than Watchman. 

The `develop` branch of the plugin has an early version of this feature available for anyone who wants to help test it (with the disclaimer that you definitely want to use this in a version-controlled project in case something goes wrong). The basic functionality is up and running and works well in the basic cases I've tested, and the plan is to use it for the next couple of weeks to catch edge cases and make sure there are no performance issues / conflicts with other plugin features. 

In particular, I want to figure out how to handle terminal buffers better. At the moment, the plugin simply calls `:edit` on the moved file, which replaces whatever was in the terminal buffer and is sure to annoy anyone using a terminal file manager inside Neovim. Replicating coc's solution left terminal buffers alone but made `lsp.buf.execute_command()` behave as if the file wasn't loaded at all (meaning imports never updated), so I have to investigate.

**Comment by jose-elias-alvarez** [comment]
Small update: renaming from terminal buffers is still not ideal, but it's less annoying and should be good enough for now. I've added handling for directories, and the watcher is at the point where it reliably handles my (limited) use cases on work projects. I'm not working most of this week, so I'm aiming to test it out more and merge it into `main` as an experimental feature early next week if everything looks OK.

**Comment by marcelbeumer** [comment]
Hi @jose-elias-alvarez I just had the thought "another watcher running in the background?". Would it be better use of resources and also a better dev UX when there is a command like `:LspFigureOutMovedFiles` or so? Assuming this is doable within a git repo (and otherwise not support the feature or have `:LspSnapshotBeforeMove` or whatever). 

I loved that vscode is able to update imports but sometimes also got annoyed with the editor immediately asking me questions while still moving files around a bit. 

Or combination of both models (keep track of changes & manual trigger)?

Didn't think it through much, just wanted to share! Thanks for your work, much appreciated!

**Comment by jose-elias-alvarez** [comment]
Thanks for the kind words! I agree with the general feeling about watchers, and I'll point out that the libuv solution is about as lightweight as a watcher can get, since it runs entirely through Neovim itself. I also agree that VS Code-style confirmation prompts can be a bit annoying, so I set up the implementation here to not require confirmation by default (though prompts can be enabled). 

If you have a chance to try the feature, I'd be interested to hear your thoughts regarding resource usage and the overall experience. If the goal is to make manual confirmation less painful and if there's demand, I could imagine tweaking the watcher to keep track of changes and apply them on demand.

As far as minimizing resource usage, the idea of using Git as a watcher is really interesting, though I'd have to look into it more or get help from someone with more knowledge of Git plumbing than me. As far as I know, Git doesn't have any easy way to get a list of renamed files (and its algorithm for detecting whether a file was renamed isn't perfect, either), and it doesn't directly handle directories, either.

**Comment by marcelbeumer** [comment]
Don't know about those detail of git either, what you say doesn't sound promising ;) Libuv & lightweight: ah that sounds great.

I tried the update functionality and it doesn't work for me so wel. Would have to make time to try on a codebase I can share with, but my setup is this: https://github.com/marcelbeumer/dotfiles/pull/1/commits/f60d425a5b62a1878bae9e8bb06f89927f03f022

Findings (running d21761d):
- Import paths are updated on open buffers, not on other files in repo
- Only works for me when I rename on the CLI, not when using NERD Tree (both cases I get the dialog asking to update imports)
- Turning on/off confirmation didn't seem to make a difference

**Comment by jose-elias-alvarez** [comment]
@marcelbeumer Thank you for taking the time to test it and for the details! 

For the NERDTree issue: I've actually been working on (and just pushed) a commit that improves handling when moving files with a non-standard buffer focused. I briefly installed and tried out NERDTree, and it seems to be working with the latest commit (and I confirmed that it wasn't working with the commit you linked). Could you pull the changes and give it a try when you have a chance?

For the first issue: executing the code action should cause the editor to load all of the files that need to be updated, so it's strange that it's not working. What's the output from `:ls` after you move a file? Also, are your files located in `/src`, relative to your `package.json` / `tsconfig.json`? I haven't been able to replicate the issue on any of my repositories, so a minimal reproduction would be a big help.

**Comment by marcelbeumer** [comment]
Yes both cli and NERDTree now works with latest commit (6ec4b14)! I now realize why some of my testing went wrong: I sometimes only opened a non-TS file, so the lang-server (and your utils) wasn't always started yet, sorry. Even moving directories works, wonderful!

**Comment by jose-elias-alvarez** [comment]
Great to hear! Now that non-standard buffer handling is in better shape, I'm hoping to get this merged today.

**Comment by Bhanukamax** [comment]
Hi, how do I test this? is it the `:TSLspRenameFile` command? that updates the import paths to the file being moved, but it doesn't update the imports which are inside the file being renamed, I mean when moving to a different directory. 

And I tried moving files with `netrw` and neovim term and `nvim-tree.lua` these didn't do anything though.

**Comment by jose-elias-alvarez** [comment]
@Bhanukamax Take a look at the readme for the develop branch, under Experimental Features – it's enabled separately and has a few settings you'll need to set up to get it working.

**Comment by jose-elias-alvarez** [comment]
Merged today, so I'm closing this issue! Please report feedback / problems in a new issue.
