### ISSUE TITLE
Handle Code Actions: "Move to a new file" generating an empty file?

### ISSUE THREAD

**Issue by Bhanukamax** [jose-elias-alvarez/nvim-lsp-ts-utils#21]
Hi this is an issue I have also raised on the neovim repo as well.

Basically the issue is when we call Code Actions on a function name and call the "Move to a new file" option, it just creates an empty file with the function name, where as what it should do is move the required code and the related imports to the new file and put an import to that file on the current file.

This is something already working fine on the coc-tsserver, this is my main blocker in getting to the neovim lsp, because I'm extensively using that functionality with the coc-tsserver.

Basically the reason behind the issue is that tsserver returns a range of -1 for all the values for the code snippet for the new file to be created.

<details>
<summary>snippet</summary>
<pre>
<code>
 [
               "file:///home/bm/code/try-lsp/ts/myNewFunc.ts"
            ]"="{
               {
                  "newText =""import { testing } from \"./testing\";\n\nexport function myNewFunc(): void {\n    testing();\n}\n",
                  "range ="{
                     "end ="{
                        character = -1,
                        line = -1
                     },
                     "start ="{
                        character = -1,
                        line = -1
                     }
                  }
               }
            }
         }
</code>
</pre>
</details>

This is a the usual behavior of the tsserver, not sure if it's a bug or the expected behavior. But that just what it is and at least vscode has no issues with that it seems. Cannot say about coc-tssever, since `coc` have their own client and server.

However what i noticed is even on emacs lsp-mode, they've come accross the same [issue](https://github.com/emacs-lsp/lsp-mode/issues/1582), and what I understood from their [PR](https://github.com/emacs-lsp/lsp-mode/commit/e7d13396e85694f52438ffd6fdf0f32ff04489bc) to fix it is, they manually rewrite those -1's to 0's before handling it.

I wonder if this is something possible to handle/develop with this util?

Following is a link to the issue I've raised on the neovim repo:
[Typescript: "Move to a new file" generates an empty file](https://github.com/neovim/neovim/issues/14469)

**Comment by jose-elias-alvarez** [comment]
It’s definitely possible for the plugin to fix the issue, since it can fix the text edit range before passing the code action on to the handler (not quite as clean as how the lsp-mode folks handled it, but not so bad, either). 

I’m curious to know why this issue occurs in the first place and whether it’s fundamentally a typescript-language-server or a tsserver issue.  Are other editors able to handle a -1 range? Do other code actions have the same problem? (It seems like the lsp-mode fix applies to all text edits, so I wonder if that’s necessary here, too.)  

My feeling is that if two editors have had to deal with this, we should probably work on fixing it upstream, but I can also put it in as a workaround for now. Let me know if you have any more info about this and I’ll see what I can find out.

**Comment by jose-elias-alvarez** [comment]
I looked into this a bit more, and I can see that ranges are [defined in the LSP specification](https://microsoft.github.io/language-server-protocol/specification#range) as zero-based, meaning that VS Code and coc-tsserver must have some kind of special handling for `-1` ranges. I don't see any specific code in typescript-language-server about these ranges, either, so it's probably just returning whatever tsserver gives it. I'll most likely open an issue for typescript-language-server to see what they think and if there's any chance of modifying the ranges for LSP compliance on their end. 

For the moment, I've just pushed a quick implementation of the feature to the plugin's `develop` branch which handles the case in your issue on the Neovim repo, and I'll merge it into `main` once I've had the chance to write tests.

**Comment by Bhanukamax** [comment]
hey thanks a lot for adding it, I tried it, and it works perfectly.

Yeah it's worth getting it fixed on the upstream, I tried to poke around in typescript repo as well as the `typescript-language-server` I couldn't figure much out, I have zero experience on the subject.

**Comment by Bhanukamax** [comment]
hey @jose-elias-alvarez , now that we have this working, do you think it's a good idea to close the issue I opened in the neovim repo?

**Comment by jose-elias-alvarez** [comment]
Glad to know it works! And yes, I think it'd be best to close the issue, since it seems to be more of an issue with tsserver than Neovim.

**Comment by Bhanukamax** [comment]
Hey thanks a lot for working on this, I've closed the issue on `neovim` with instruction on how to use this plugin with the develop branch.

**Comment by Bhanukamax** [comment]
sorry mistakenly I hit the close button :) , and reopened to keep it open as you said.

**Comment by jose-elias-alvarez** [comment]
Merged today!
