### ISSUE TITLE
Feature Request: Allow disabling eslint functionality

### ISSUE THREAD

**Issue by marcelbeumer** [jose-elias-alvarez/nvim-lsp-ts-utils#22]
Would be great to have a `enable_eslint = false` or so in the options.

By installing `eslint_d` you only feel the startup time once, but I usually don't use eslint while editing code and prefer completely disabling it.

**Comment by jose-elias-alvarez** [comment]
I'm a little confused – are you referring to diagnostics? If so, there is an `eslint_enable_diagnostics` settings that (I think) does what you want. Or do you mean that you want to start Neovim with diagnostics disabled and potentially toggle them later?

**Comment by marcelbeumer** [comment]
No I meant to also disable eslint for code actions, for which I can only set a different `eslint_bin` as far as I can see. 

(I noticed as suddenly my code action became very slow, then installed `estlind_d` but rather not)

**Comment by jose-elias-alvarez** [comment]
Ah, understood. The lack of a setting to disable code actions is a bit of a relic, but I can see that it's necessary, especially for users who don't want to switch to `eslint_d`. It should be trivial to implement, so I'll take care of it the next time I work on the plugin (or a PR would be appreciated!).

**Comment by marcelbeumer** [comment]
Great! I still have to get my hands dirty with Lua dev, this may be a good opportunity, feel free to assign to me, will make some time somewhere this week.

**Comment by jose-elias-alvarez** [comment]
Awesome, let me know if you need any guidance on this.
