### ISSUE TITLE
Can eslint be disabled?

### ISSUE THREAD

**Issue by cjnucette** [jose-elias-alvarez/nvim-lsp-ts-utils#24]
Hi, I'm using `deno` and I don't need `eslint` to be active. Is there a way to disable it? I think one way to disable `eslint` would be the absence of a `.eslintrc` in the current folder. 
Great plugin by the way.

PS: I don't `tsserver` active either, for that matter.

**Comment by jose-elias-alvarez** [comment]
When you say disable `eslint`, are you referring to code actions? If so, we recently added a setting, `eslint_enable_code_actions`, that will allow you to disable them (it wasn't properly documented in the readme, but I just added it).

I'm curious – what features of the plugin are you using with Deno? Either way, the plugin won't start or interact with `tsserver` or `typescript-language-server`. I haven't tested it with any other servers, but theoretically it'll hook into whatever client you are using.

**Comment by cjnucette** [comment]
I want to disable `eslint` because it is complaining that there isn't a `.eslintrc` file which is not necessary with a `deno` project. On the other hand `typescript` is giving linting error when you use an extension when importing a file, but this the way you import files with `deno`. The only linting in a `deno` project should come from `deno` itself.

**Comment by jose-elias-alvarez** [comment]
I see. ESLint diagnostics are only active if you explicitly set `eslint_enable_diagnostics = true`, so setting it to `false` (or deleting that line completely) should prevent you from seeing any ESLint output from this plugin.

For the second issue: If you call nvim-lspconfig's `tsserver.setup` function in your LSP configuration, it will enable `tsserver` diagnostics for all TypeScript files. You could try moving the plugin's `ts_utils.setup` into your Deno LSP `on_attach` function, but the plugin fundamentally depends on `typescript-language-server` for the majority of its functions, and I don't think it will work well.

**Comment by cjnucette** [comment]
Ok, thanks.
