### ISSUE TITLE
Error while updating with packer

### ISSUE THREAD

**Issue by vuki656** [jose-elias-alvarez/nvim-lsp-ts-utils#25]
I've had trouble updating it for the past couple of days.

![image](https://user-images.githubusercontent.com/8104698/119237253-306fd780-bb3c-11eb-8cf2-73948ffe252f.png)

Let me know what info you need to debug.

**Comment by jose-elias-alvarez** [comment]
Which branch are you using? I think there might have been an issue with the history for the `develop` branch. Either way, could you try uninstalling and re-installing the plugin? I find that that tends to solve Packer issues for me.

**Comment by vuki656** [comment]
It was on develop at first, yeah, but even after removing a specific branch, it was happening.

Reinstalling it completely fixes it, thanks.
