### ISSUE TITLE
Watcher doesn't watch root level js,ts files

### ISSUE THREAD

**Issue by aridgupta** [jose-elias-alvarez/nvim-lsp-ts-utils#31]
I think the watcher doesn't watch root level js,ts files. Hence, the file formatting doesn't work in these files.

**Comment by jose-elias-alvarez** [comment]
You're right that the watcher doesn't watch files at the root level, but that shouldn't affect formatting, since the two are independent. Are you sure that `tsserver` itself is attaching to those files? You should see both `tsserver` and `null-ls` in `:LspInfo`. Also, is there anything in the debug logs?

**Comment by aridgupta** [comment]
Both `tsserver` and `null-ls` are attached to the client. However, the debug message shows `vim.lsp.buf.formatting_sync: timeout`

**Comment by jose-elias-alvarez** [comment]
Can you try with `vim.lsp.buf.formatting()`?

**Comment by aridgupta** [comment]
It doesn't work. Also, `:messages` didn't show any errors.

**Comment by jose-elias-alvarez** [comment]
No idea about this one, I can't replicate it, and if `tsserver` attached, there's no logical reason why it wouldn't format files in the root directory. 

Does the same thing happen with other formatters? Does the same formatter work from the command line? I assume files not in the root directory are being formatted correctly, right?

To be clear, there's no output at all from null-ls in `:messages`, even with `debug = true`?

**Comment by aridgupta** [comment]
I am sorry for all the troubles. This was all because of my mistake. I had a typo in `.prettierrc.js` and it messed everything up. Closing this now.

**Comment by jose-elias-alvarez** [comment]
No worries, thanks for confirming!
