### ISSUE TITLE
Show source and code of linting issue?

### ISSUE THREAD

**Issue by mgutz** [jose-elias-alvarez/nvim-lsp-ts-utils#45]
vscode shows the source of the linting issue (eslint or typescript) and the code for the failed rule. It's hard to disable errors or find online solution without this info. Is that possible with this plugin?

**Comment by jose-elias-alvarez** [comment]
Both of these are actually available but not shown by the built-in diagnostics handlers. I recommend [trouble.nvim], which will show you both the source and the rule ID (and generally provide a more VS Code-like experience with diagnostics).
