### ISSUE TITLE
[BUG] Disable rule in file appends the disable comment at the end of the file

### ISSUE THREAD

**Issue by jorrete** [jose-elias-alvarez/nvim-lsp-ts-utils#58]
### FAQ

- [X] I have checked [troubleshooting](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils#troubleshooting) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils/issues?q=is%3Aissue+) and there are no issues with the same problem.

### Neovim Version

0.5.0

### Steps to reproduce

Open a javascript file with some error eslint errors in it.
Launch code actions and select disable rule for the entire file.

### Expected behavior

The comment disabling the rule should appear at the beginning of the file.

### Actual behavior

The comment disabling the rule appears at the end of the file.

### Help

No

**Comment by jose-elias-alvarez** [comment]
Whoops! Should be fixed by 685f88c069dbdf013960523958cf874c7d39cbdd. Can you update and let me know?

**Comment by jorrete** [comment]
Yes, fixed with that commit.
Thanks for your work!
