### ISSUE TITLE
[FEATURE REQUEST]  eslint yarn pnp support

### ISSUE THREAD

**Issue by academo** [jose-elias-alvarez/nvim-lsp-ts-utils#83]
### Issues

- [X] I have checked [existing issues](https://github.com/jose-elias-alvarez/nvim-lsp-ts-utils/issues) and there are no existing ones with the same request.

### Feature description

I've been trying to setup eslint using yarn pnp but the current `eslint_bin` will only accept a fixed value of `eslint` or `eslint_d`. 

With yarn pnp the eslint binary would be somewhere like `./.yarn/sdks/eslint/bin/eslint.js` and it is not necessarily part of your PATH

There is a validation  that only allows specific values for the `eslint_bin` and I wonder if removing such validation would be enough to make yarn pnp work.

If there is another way that someone made this work with yarn pnp please let me know.

### Help

Yes, but I don't know how to start. I would need guidance

### Implementation help

I managed to make eslint with this setup:

```lua
local eslint_command = 'eslint'
local pnp_eslint = vim.fn.findfile('.yarn/sdks/eslint/bin/eslint.js');
if (pnp_eslint) then eslint_command = pnp_eslint end


local null_ls = require('null-ls')
local sources = {
    null_ls.builtins.diagnostics.eslint.with({command = eslint_command})
}
require("null-ls").config {sources = sources}
```

but of course this doesn't work with the code actions and other functionalities.

_No response_

**Comment by jose-elias-alvarez** [comment]
Just removing the validation wouldn't work, since it would still try to find an executable in `node_modules` and fall back to the global executable if it's not available. 

I haven't tried Yarn PnP yet but would accept a PR adding support until I get around to it. An easier alternative may be to try the [ESLint language server](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#eslint).

**Comment by academo** [comment]
@jose-elias-alvarez what about accepting a command to execute and trust it if passed? instead of searching for the command traversing the disk?

**Comment by jose-elias-alvarez** [comment]
As you noted, you can currently do that via null-ls for diagnostics (and you can do the same for formatting). It's not currently possible for code actions – I'd have to spin it out as an independent source, but honestly I'm not sure it's worth the effort given that the language server does the same thing but better (I'd accept a PR, though).

**Comment by non25** [comment]
Wanted to open this issue myself on last weekend. :grin: 

I tried making a script in PATH which looks like this:

```sh
#!/bin/sh
/home/non/path-to/your/eslint_d.js "$@"
```

Though I could trick the system, but looks like no success. :grin: 

```
 Client: null-ls (id: 2, pid: 5001, bufnr: [1, 1])
 	filetypes:       javascript, javascriptreact, typescript, typescriptreact, javascript.jsx, typescript.tsx
 	autostart:       false
 	root directory:  /home/non/some-project
 	cmd:             nvim
```

This is from neovim's LspInfo.

Sad times.

**Comment by jose-elias-alvarez** [comment]
@non25 If possible I recommend trying the [language server](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#eslint). It still has a few bugs to work out but it's generally reliable, and it looks like there is a [workaround](https://github.com/NICHTJ3/nvim-lsp-installer/blob/cba025927930f7339b973a3c0ba5ed469b5ad0a7/lua/nvim-lsp-installer/servers/eslint/README.md) to use Yarn PnP.
